#NAME: Roselyn Lee,Chris Baker
#EMAIL: removed for partners privacy
#ID: removed for partners privacy

default: 
	rm -f lab3b
	ln lab3b.py lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-705084326.tar.gz lab3b

dist:
	tar -czvf lab3b-705084326.tar.gz lab3b.py README Makefile
