#NAME: Roselyn Lee,Chris Baker
#EMAIL: roselyn.lee@gmail.com,cbaker24@g.ucla.edu
#ID:705084326,105180929 

default: 
	rm -f lab3b
	ln lab3b.py lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-705084326.tar.gz lab3b

dist:
	tar -czvf lab3b-705084326.tar.gz lab3b.py README Makefile
